# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

resources:
  repositories:
  - repository: inprocess-frontend
    name: inprocess-frontend
    type: git

variables:
  imageRepository: 'inprocess-$(Build.SourceBranchName)'
  dockerRegistryServiceConnection: 'mindpath-acr-dev'
  containerRegistry: 'mindpathregistrydev.azurecr.io'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
      path: s/inprocess-backend
    - checkout: inprocess-frontend
      path: s/inprocess-backend/inprocess-frontend
    - script: |
        cd $(Build.SourcesDirectory)/inprocess-backend/inprocess-frontend
        git checkout $(Build.SourceBranchName)
      displayName: Branch Changed
    - task: Docker@2
      displayName: Build and push image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: '$(Build.SourcesDirectory)/inprocess-backend/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest